### ISSUE TITLE
User story 10: Prompts

### ISSUE THREAD

**Issue by bierlingm** [bierlingm/capstone-project#12]
## Value Statement
As a **meditator**
I need **prompts**
So that **I can focus my session on something specific**

## Description (Text, Scribble, Wireframe, Design)
- Every meditation session begins with a random prompt in the form of text alongside the button to start writing
- The user can shuffle prompts to get a new prompt

## Acceptance Criteria
- [x] There is a text prompt upon loading a session
- [x] It fits with the general style of the app
- [x] There is a shuffle button that loads a new prompt into view

## Tasks
- [x] Create feature branch
- [x] Create components (Prompt) in Storybook
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

## Size
M
