### ISSUE TITLE
User story 4: Session notes

### ISSUE THREAD

**Issue by bierlingm** [bierlingm/capstone-project#14]
## Value Statement
As a **frequent meditator**
I need **the ability to take session notes**
So that **I can retain insights from, and reflect on, a session**

## Description (Text, Scribble, Wireframe, Design)
- After finishing a writing session, a new screen appears with the question "Do you want to take notes on this session"? and two buttons ("yes", "no")
- Clicking yes leads you to another screen with a text input for notes and a "save" button which saves the note to local storage
- Clicking no ends the session and takes you back to the starting screen
- Every writing session gets saved to a JSON file in local storage with info about date and time, content of the session, and notes

## Acceptance Criteria
- [] After finishing a writing session, a new screen appears with the question "Do you want to take notes on this session"? and two buttons ("yes", "no")
- [] Clicking yes leads you to another screen with a text input for notes and a "save" button which saves the note to local storage
- [] Clicking no ends the session and takes you back to the starting screen
- [] Every writing session gets saved to a JSON file in local storage with info about date and time, content of the session, and notes

## Tasks
- [] Create feature branch
- [] Create components (note field, yes/no/save buttons) in Storybook
- [] Write component tests
- [] Add components to app (feature implementation with state)
- [] Add missing styles

## Size
L
