### ISSUE TITLE
User story 9: Tutorial

### ISSUE THREAD

**Issue by bierlingm** [bierlingm/capstone-project#15]
## Value Statement
As a **new user**
I need **a tutorial**
So that **I can learn what the app is about and how to use it**

## Description (Text, Scribble, Wireframe, Design)
- A screen that lets you swipe through several explanatory images

## Acceptance Criteria
- [] The screen shows all stages of the meditation/writing session
- [] The tutorial is swipe-able
- [] You can skip the tutorial
- [] It is accessible through a "?" button on the startup screen, even after initial completion

## Tasks
- [] Create feature branch
- [] Create components (skip button, "?" button) in Storybook
- [] Write component tests
- [] Take screenshots of the stages
- [] Add components to app (feature implementation with state)
- [] Add missing styles

## Size
M
