### ISSUE TITLE
User story 12: Home screen

### ISSUE THREAD

**Issue by bierlingm** [bierlingm/capstone-project#16]
## Value Statement
As a **new user**
I need **a home screen**
So that **I can choose which functionality of the app to engage**

## Description (Text, Scribble, Wireframe, Design)
- A home screen that welcomes you
- It has options: start a session, view previous sessions, view/edit prompts

## Acceptance Criteria
- [] The screen allows the user to access all features
- [] It is the startup screen

## Tasks
- [] Create feature branch
- [] Create components (feature buttons) in Storybook
- [] Write component tests
- [] Add components to app (feature implementation with state)
- [] Add missing styles

## Size
M
