### ISSUE TITLE
User story 6: Prompt sequences

### ISSUE THREAD

**Issue by bierlingm** [bierlingm/capstone-project#17]
## Value Statement
As a **power user**
I need **a way to chain prompts and writing**
So that **I can reliably get into a certain headspace**

## Description (Text, Scribble, Wireframe, Design)
- The user can chain sessions by selecting a button on the session config screen

## Acceptance Criteria
- [] The user has a way to configure and run sequences of prompts

## Tasks
- [] Create feature branch
- [] Create components (sequence button) in Storybook
- [] Write component tests
- [] Add components to app (feature implementation with state)
- [] Add missing styles

## Size
L
